[package]
name = "font_decoder"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
encoding_rs = "0.8.33"
enum_fonts = { version = "0.1.0", path = "../enum_fonts" }
num_enum = "0.7.1"
